parser: "@typescript-eslint/parser"

parserOptions:
  project: 'tsconfig.json'
  tsconfigRootDir: '.'

extends:
  - plugin:@typescript-eslint/recommended
  - plugin:prettier/recommended
  - prettier/@typescript-eslint
  - prettier/react

plugins:
  - "@typescript-eslint"
  - prettier

rules:
  "@typescript-eslint/no-namespace": off
